export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
export const CLEAR_STORE_DATA = 'CLEAR_STORE_DATA';
export const SET_NICKNAME = 'SET_NICKNAME';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
