export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
export const CLEAR_STORE_DATA = 'CLEAR_STORE_DATA';
export const SET_NICKNAME = 'SET_NICKNAME';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';

// WS = WEBSOCKET
export const WS_CONNECT = 'WS_CONNECT';
export const WS_DISCONNECT = 'WS_DISCONNECT';
export const WS_SEND_MESSAGE = 'WS_SEND_MESSAGE';
export const WS_RECEIVE_MESSAGE = 'WS_RECEIVE_MESSAGE';
export const WS_CONNECT_SUCCESS = 'WS_CONNECT_SUCCESS';
